language: php

php:
    - 8.0

install:
    - travis_retry composer self-update
    - travis_retry composer clear-cache
    - travis_retry composer install --no-interaction --no-suggest

script:
  - ./vendor/bin/phpunit --bootstrap vendor/autoload.php